name: cb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.2
  - pandas=1.4.3
  - matplotlib=3.5.2
  - geopandas=0.11.1
  - ipykernel 
  - nbformat
  - pip
  - pip:
    - mpld3
    - plotly
    - chart_studio 
    - python-dotenv


