name: water-access-original
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Latest stable Python version
  - numpy  # Latest compatible version
  - pandas  # Latest compatible version
  - matplotlib  # Latest compatible version
  - ipykernel 
  - ipywidgets>=7.6
  - notebook>=5.3
  - Flask=3.0.3
  - pycountry 
  - pyarrow  # For Parquet support
  - scipy  # Latest compatible version
  - pyinterpolate
  - weightedstats
  - pytest=8.0.2
  - openpyxl=3.1.5
  - rasterio
  - geopandas
  - scikit-learn
  - rasterio
  - pip:
    - plotly
    - tabulate
    - kaleido
    - chart_studio 
    - python-dotenv
    - dash_bootstrap_components
    - jupyter-dash
    - jupyterlab-dash
    - countryinfo
    - seaborn
