name: water-access-original
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.2
  - pandas=1.4.3
  - matplotlib=3.5.2
  - ipykernel 
  - ipywidgets>=7.6
  - notebook>=5.3
  - Flask=3.0.3
  - pycountry 
  - pyarrow  # Added for Parquet support
  - pip
  - dash
  - scipy
  - pyinterpolate
  - weightedstats
  - pytest=8.0.2
  - openpyxl=3.1.5
  - rasterio
  - geopandas
  - scikit-learn
  - pip:
    - plotly
    - tabulate
    - kaleido
    - chart_studio 
    - python-dotenv
    - dash_bootstrap_components
    - jupyter-dash
    - jupyterlab-dash
    - countryinfo
    - seaborn
