name: water-access
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Latest stable Python version
  - numpy  # Latest compatible version
  - pandas  # Latest compatible version
  - matplotlib  # Latest compatible version
  - ipykernel 
  - ipywidgets>=7.6
  - notebook>=6.4  # Updated notebook version
  - jupyterlab  # For a modern Jupyter interface
  - Flask>=2.3.2  # Latest stable version of Flask
  - werkzeug>=2.3.7  # Latest stable version of Werkzeug
  - pycountry 
  - pyarrow  # For Parquet support
  - scipy  # Latest compatible version
  - pyinterpolate
  - weightedstats
  - dash
  - pytest>=7.4.0  # Latest stable version of pytest
  - pip
  - pip:
    - plotly
    - kaleido
    - chart_studio 
    - python-dotenv
    - dash_bootstrap_components
    - jupyter-dash
    - jupyterlab-dash
    - countryinfo
