name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Running Tests
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo
      - uses: actions/checkout@v3

      # 2) Set up Miniconda, creating & activating the environment from environment.yml
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: water-access
          # use-mamba speeds up conda installs
          use-mamba: true

      # 3) Run pytest inside the activated conda env
      - name: Test with pytest
        run: mamba run -n water-access pytest

