name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Running Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      # 1) Set up Conda environment
      - name: Set up Miniconda ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          auto-activate-base: false
          activate-environment: water-access
          use-mamba: true

      # 2) Install dependencies (including local code in editable mode)
      - name: Install dependencies
        run: |
          conda run -n water-access pip install --upgrade pip
          conda run -n water-access pip install -e .
          if [ -f requirements.txt ]; then conda run -n water-access pip install -r requirements.txt; fi

      # 3) Test with pytest
      - name: Test with pytest
        run: |
          conda run -n water-access pytest
